Feature coin table
Chase-T-White/Crypto-App pull request #3
Opened 2024-06-16 02:37 UTC by Chase-T-White

1. Created dark/light mode theme
2. Created Coin table with infinite scroll
3. Moved some files around

2024-06-17 15:18 UTC, yoloOnTheBattlefield requested changes

2024-06-17 15:18 UTC, yoloOnTheBattlefield commented on app/ui/home/CryptoCoinTable.tsx
> +    );
no nested ternaries

2024-06-17 15:18 UTC, yoloOnTheBattlefield commented on app/ui/home/CryptoCoinTable.tsx
> +            })
extrapolate this in a function

2024-06-17 15:18 UTC, yoloOnTheBattlefield commented on app/ui/navbar/buttons.tsx
> +      {/* <Image src="/images/Light.svg" alt="Light icon" width={20} height={20} /> */}
remove this

2024-06-25 23:51 UTC, Chase-T-White commented
Issues have been resolved

2024-06-25 23:51 UTC, merged