Feature coin convertor
Chase-T-White/Crypto-App pull request #5
Opened 2024-06-29 21:19 UTC by Chase-T-White

- Adding coin convertor functionality
- Adding coin convertor chart
- Adding time scale buttons for coin convertor chart

2024-06-30 15:14 UTC, yoloOnTheBattlefield requested changes

2024-06-30 15:14 UTC, yoloOnTheBattlefield commented on app/ui/home/TimeScaleSelection.tsx
> +        onClick={(e) => handleClick(e)}
onClick={handleClick}

2024-06-30 15:14 UTC, yoloOnTheBattlefield commented on app/ui/home/convertor/CoinConvertorChartSection.tsx
> +            onClick={(e) => handleClick(e)}
same here

2024-07-01 18:32 UTC, Chase-T-White commented on app/ui/home/TimeScaleSelection.tsx
> +        onClick={(e) => handleClick(e)}
issue has been addressed

2024-07-01 18:32 UTC, Chase-T-White commented on app/ui/home/convertor/CoinConvertorChartSection.tsx
> +            onClick={(e) => handleClick(e)}
issue has been addressed

2024-07-01 18:34 UTC, merged